### PR TITLE
Correct chmod path and incorporate build information

### PR DESCRIPTION
**Pull request by martijndeb**
Updates the chmod line in the Makefile to the correct path. Adds build version number and build datetime.
Proposes version 0.1.0 for the version information.

### CODE REVIEW

**Comment by martijndeb** [comment]
Some minor improvements :-). Happy hacking!

**Comment by thimc** [comment]
> Some minor improvements :-). Happy hacking!

Thank you so much for the pull request!

Unfortunately I am getting some sort of an error when make tries to evaluate the result of the date command.
It is compiling the executable as expected but it also spits out the following:

```
  $ make
  Bad modifier: %M:%SZ')
  go build -ldflags "-X main.version=0.1.0 -X main.buildTime=" -o tinyirc main.go
```
I am thinking there must be some sort of GNUism in your pull request because running it with GNU Make returns no warnings or similar. The date command per say is not the issue here, running `date -u '+%Y-%m-%dT%H:%M:%SZ'` works fine.

EDIT: By applying the commit 483c5f53007b3ee9ceaf80c62a14a1f2cbc4cdc8 I am able to compile tinyirc with both BSD and GNU make. Let me know what you think.

**Comment by martijndeb** [comment]
I see, I compiled on Debian 11, no issues there. But your fix is appropiate. I guess it has some problems with %M in the setup I took, as it might interfere with a shell modifier. Backticking it is a good solution 👍🏻

**Comment by thimc** [comment]
Very well, I will merge this then! Thanks a lot :)

**Pull request merged**
